### ISSUE TITLE
No Keep Duplicate feature? Terrible

### ISSUE THREAD

**Issue by shutupthanks** [Spegeli/PokemoGoBot-GottaCatchEmAll#370] opened 2016-08-12 00:03 UTC
It just transferred half of my high IV Pokemon duplicates before I noticed and turned it off. Completely useless for anyone but account sellers to power level.

**Comment by XiCynx** [comment] 2016-08-12 00:07
That's your fault because you didn't thoroughly check the settings before you started it.  If you would have changed the amount of duplicate IV pokemon to keep to a number higher than 1 it wouldn't have transferred them.  If you would have favorited any of the pokemon you didn't want to transfer they would still be there, or if you would've added any pokemon you had of high IV to the Do Not Transfer List, they would still be there.  Next time be more careful.

**Closed by XiCynx** 2016-08-12 00:07 UTC

**Comment by shutupthanks** [comment] 2016-08-12 23:48
Lol no you idiot, the option for duplicate Pokemon isn't even in the settings, sorry you're too stupid to grasp basic reading comprehension

Bots are dead now anyway and that garbage version is too, you pathetic clown
________________________________

**Comment by XiCynx** [comment] 2016-08-13 04:18
Wait... Oh, what's this I see here?  You've got to be kidding me!  Unless my eyes deceive me, I swear outlined and highlighted in yellow are the settings to tell the bot how many of each pokemon to keep!  Who would've ever thought to read through these settings and change them to an amount higher than 1 to keep more than 1 duplicate of each pokemon!  Crazy!

TransferPokemonKeepAmountHighestCP = 1
TransferPokemonKeepAmountHighestIV = 1

Change those numbers to 3/4/5/6/7/8/9 and guess what?  None of your duplicate high IV pokemon would have been transferred!  Man, it sure does pay to read the settings.  This is why I'm a moderator and you're not.  Sorry :(

![transferamount](https://cloud.githubusercontent.com/assets/20632191/17641376/174af3d0-60eb-11e6-8e23-1e98a8588331.png)

**Comment by shutupthanks** [comment] 2016-08-13 18:36
Lol no one gives a shit your stupid ass is a mod on some site you loser, the fact remains there's no setting for keeping duplicate Pokemon like literally every other bot made by guys who know what they're doing have in theirs, your outdated and not irrelevant shit bot is garbage for multiple reasons, not just the fact you used obtuse language for keep dupes. Have fun being an inept clown for your sad life lmaooooooo that's why I'm a mod, you said it like you think it's important, you pathetic loser. ?
________________________________

**Comment by WithoutSkil** [comment] 2016-08-13 18:39
Well i guess you got outplayed... 
And for you claim of obtuse language, what a load of crap.

If you cannot read a simple settings file, go to buddy forums.. I heard they have bots for noobs.

**Comment by XiCynx** [comment] 2016-08-13 18:56
Thank you @WithoutSkil 
I'm glad you understand, I didn't make the bot, a man who's first language is German did.  So the use of how the names are in the Settings are a reflection of that.  I don't think it's very hard to read:

TransferPokemonKeepAmountHighestCP = 1
TransferPokemonKeepAmountHighestIV = 1

To me, it tells me this.  'TransferPokemon' (okay, it's part of the transfer feature), 'KeepAmount' (okay, this is part of how many I want to keep), 'HighestCP/IV' (okay, I'm keeping pokemon with the higher CP and/or IV).  Pretty cut and dry.


What really makes me wonder if he even ready my reply is @shutupthanks said: "the fact remains **there's no setting for keeping duplicate Pokemon** like literally every other bot made by guys who know what they're doing have in theirs", when I literally explained the EXACT settings he needs to use to keep duplicate Pokemon.  /mindblown
